name: solvecasejiit
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^3.1.6
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  fluttertoast: ^4.0.0
  getflutter: ^1.0.11
  flutter_spinkit: ^4.1.2
  url_launcher: ^5.4.11
  fluid_bottom_nav_bar: ^1.0.1
  cupertino_icons: ^0.1.3
  persistent_bottom_nav_bar: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

